apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spm-secrets
  namespace: spm
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/replace-with-gcp-project-id/secrets/database-url/versions/latest"
        path: "database-url"
      - resourceName: "projects/replace-with-gcp-project-id/secrets/service-config/versions/latest"
        path: "service-config"
