apiVersion: v1
kind: ServiceAccount
metadata:
  name: spm-microservices
  namespace: spm
  labels:
    app.kubernetes.io/part-of: spm
  annotations:
    iam.gke.io/gcp-service-account: replace-with-microservices-service-account-email
