apiVersion: v1
kind: ServiceAccount
metadata:
  name: spm-microservices
  namespace: spm
  annotations:
    iam.gke.io/gcp-service-account: replace-with-terraform-output-microservices-service-account-email
